# Generated by Django 2.2.6 on 2019-10-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_name', models.CharField(db_index=True, help_text='Please input boat model', max_length=20, unique=True, verbose_name='Boat model')),
                ('boat_length', models.FloatField(help_text='Please input boat water-line length', verbose_name='Boat water-line length')),
                ('boat_description', models.TextField(blank=True, help_text='Please describe the boat', verbose_name='Boat description')),
                ('boat_mast_type', models.CharField(choices=[(None, 'Please choose  the rigging type'), ('SL', 'Sloop'), ('KE', 'Ketch'), ('YA', 'Yawl'), ('CK', 'Cat Ketch'), ('CU', 'Cutter')], help_text='Please input boat rigging type', max_length=10, verbose_name='Boat rigging type')),
                ('boat_price', models.PositiveIntegerField(help_text='Please input boat price', verbose_name='price of the boat')),
                ('boat_sailboatdata_link', models.URLField(blank=True, help_text='Please type in URL to Sailboatdata page for this boat', max_length=100, verbose_name='URL to Sailboatdata')),
                ('boat_keel_type', models.CharField(help_text="Please specify boat's keel type", max_length=50, verbose_name='Boat keel type')),
                ('boat_publish_date', models.DateTimeField(auto_now_add=True)),
                ('first_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='first manufacturing year of the model')),
                ('last_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Last manufacturing year of the model')),
                ('change_date', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Boats primary data',
                'verbose_name_plural': 'Boats primary data',
                'ordering': ['-boat_publish_date'],
            },
        ),
    ]
