# Generated by Django 2.2.6 on 2019-10-22 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsexamples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Please add a title', max_length=50, verbose_name='Article title')),
                ('content', models.TextField(blank=True, help_text='Please briefly describe the article', verbose_name='Description of the article')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published at')),
                ('url_to_article', models.URLField(help_text='Please insert URL of the article', max_length=100, unique=True, verbose_name='URL to the article')),
                ('show', models.BooleanField(default=True, help_text='Marked articles are shown everywhere, unmarkedconsidered as deleted ones', verbose_name='deleted mark')),
                ('change_date', models.DateTimeField(auto_now=True, null=True)),
                ('foreignkey_to_boat', models.ForeignKey(blank=True, help_text='Please choose the boat', null=True, on_delete=django.db.models.deletion.CASCADE, to='rsexamples.BoatModel', verbose_name='Parent boat for article')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Please type in comment here', verbose_name='Comment text')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='publish?', verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Publish date')),
                ('change_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('foreignkey_to_article', models.ForeignKey(blank=True, help_text='Please choose the article to comment on', null=True, on_delete=django.db.models.deletion.CASCADE, to='rsexamples.Article', verbose_name='Article')),
                ('foreignkey_to_boat', models.ForeignKey(blank=True, help_text='Please choose the boat to comment on', null=True, on_delete=django.db.models.deletion.CASCADE, to='rsexamples.BoatModel', verbose_name='Boat')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
